######################################################
### REVERT HEATMAP GENERATOR ~~~~~~~~~~~~~~~~~~~~~ ###
### AUTHORS: Tim Amos & Richard Edwards 2015 ~~~~~ ###
### CONTACT: richard.edwards@unsw.edu.au ~~~~~~~~~ ###
######################################################

# This script is modelled on:
# /home/tim/Documents/WhiteP.Paleovirus-Oct14/code/revert_heatmaps.R

############# ::: GENERAL SETUP ::: ##################

# Usage = Rscript rje.r basefile [options] 

## ~ Read commandline arguments ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ##
#args <- commandArgs(TRUE)   # NB. Tim used: args <- commandArgs(trailingOnly = TRUE) 
rtype = arglist$rtype        # arglist is generated by rje.r
basefile = arglist$basefile  # arglist is generated by rje.r

## ~ Setup global parameters and file names ~~~~~~~~~~~~~~~~~~~~~~~~~~ ##
settings = list(basefile=basefile)   # Access with settings[["basefile"]] or settings$basefile
settings[["ensembl.release.tdt"]] = "/Users/redwards/Documents/Projects/Paleovirus-May14/dev/2015-02-08.REVERT.R/ensembl.release.tdt"
# ensembl.release.tdt <- args[3] 
settings$value = "Coverage"  # args[4] - find out what this is used for.
settings$use.alias = TRUE    # as.logical(args[5]) 
settings$bottom.margin = 14  # <- as.numeric(args[6]) 
settings$right.margin = 6    # <- as.numeric(args[7]) 
settings$out.png = paste(basefile,".heatmaps.png",sep="")
settings$colour.viruses = TRUE   #<- as.logical(args[9]) 
settings$threshold = 10       # <- as.numeric(args[10]) 
settings$split = None        # Host|Viruses|None <- args[11] 
settings$alphabetical = TRUE  # <- as.logical(args[12]) 
settings$scatter = TRUE      # <- as.logical(args[13]) 
settings$scale = -1           # <- as.numeric(args[14])

#Usage: Rscript revert_heatmaps.R revert-ensembl.revert.tdt revert-ensembl.virus.tdt ensembl.release.tdt [Coverage|Identity] [TRUE|FALSE] 14 6 revert_heatmaps.png [TRUE|FALSE] 10 [Host|Virus|None] [TRUE|FALSE] [TRUE|FALSE] -1

arglist = argBool(arglist,c("use.alias","colour.viruses","alphabetical","scatter"))    # List of Boolean settings
arglist = argNum(arglist,c("bottom.margin","right.margin","threshold","scale"))     # List of numeric settings
for(cmd in names(arglist)){
  settings[[cmd]] = arglist[[cmd]]  # Need to add processing of booleans etc.
}

revert.tdt = paste(basefile,".revert.tdt",sep="")    #revert.tdt <- args[1]   
virus.tdt = paste(basefile,".virus.tdt",sep="")    # <- args[2] 
value = settings$value
use.alias = settings$use.alias
bottom.margin = settings$bottom.margin
right.margin = settings$right.margin
out.png = settings$out.png
colour.viruses = settings$colour.viruses
threshold = settings$threshold
split = settings$split
alphabetical = settings$alphabetical
scatter = settings$scatter
scale = settings$scale

## ~ Setup libraries for functions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ##

chooseCRANmirror(ind = 4) 
if (!require("gplots", character.only = TRUE)) { 
  install.packages("gplots", dep = TRUE) 
  if(!require("gplots", character.only = TRUE)) stop("Package not found") 
  library(gplots) 
} 
if (!require("hash", character.only = TRUE)) { 
  install.packages("hash", dep = TRUE) 
  if(!require("hash", character.only = TRUE)) stop("Package not found") 
  library(hash) 
}

############# ::: DEFINE METHODS ::: ##################

## ~ Tree of hosts or viruses ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ##

#Keep the hosts and viruses in the identity plot the same as the coverage plot 
tree <- function(val, dat, row, alpha){ 
  dd <- !(alpha) 
  if (!(alpha)) { 
    if (row) { 
      v <- rowMeans(dat, na.rm = TRUE) 
      hc <- hclust(dist(dat)) 
    } else { 
      v <- colMeans(dat, na.rm = TRUE) 
      hc <- hclust(dist(t(dat))) 
    } 
    dd <- as.dendrogram(hc) 
    dd <- reorder(dd, v) 
  } 
  return(dd) 
}

############# ::: MAIN RUN CODE ::: ##################

## ~ Load and tidy data ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ##

data <- read.table(revert.tdt, header = T, stringsAsFactors = F, sep = '\t', quote = '')

#Trim Genome names to the first fullstop and from the start of virus groups to the last full stop 
data$Genome <- sub("[.].*", "", data$Genome) 
data$VirusGB <- sub(".*[.]", "", data$VirusGB) 
data$Local <- 100.0 * data$Identity / data$Coverage 
#data <- rapply(data, f=function(x) ifelse(is.nan(x), 0, x), how="replace")
nan_rep = function(x){ ifelse(is.nan(x), 0, x)}
for (dcol in colnames(data)){
  data[[dcol]] = sapply(data[[dcol]], nan_rep)
}


# >>> START TEMP PLAY 
# Reduce data to useful data
data = data[data$Coverage > 0,]


multihits = data[data$ProtHits > 1,]
polyprot = data[data$ProtNum < 3,]
(analysis = sub(".*[/]", "", basefile) )
plot(data$Coverage,data$Local,type="n",main=analysis,xlab="%Coverage",ylab="Local %Identity")
points(polyprot$Coverage,polyprot$Local,col="red",pch=16)     # Viruses with 2+ hits
points(multihits$Coverage,multihits$Local,col="blue",pch=16)  # Viruses with < 3 proteins in total
points(data$Coverage,data$Local)
# Add overlay of the NR hits!


boxplot(data$Coverage ~ data$Genome)
boxplot(data$Coverage ~ data$Virus)

# <<< END TEMP PLAY


#Convert to a matrix and choose value display on heatmap 
data2.cov <- xtabs(Coverage ~ Virus + Genome, data = data) 
data2.loc <- xtabs(Local ~ Virus + Genome, data = data) 
if (value == 'Coverage') { 
  data2 <- data2.cov 
} else { #Identity 
  value <- "Local Identity" 
  data2 <- data2.loc 
} 
data2.id <- xtabs(Identity ~ Virus + Genome, data = data)

# Function to ???
both <- function(vec1, vec2) { 
  vec3 <- vector() 
  for (i in c(1:length(vec1))) { 
    vec3[i] = vec1[i] && vec2[i] 
  } 
  return(vec3) 
}

#Remove Genomes and Viruses with all 0s. 
pass1 <- both(apply(data2.cov, 1, max) > threshold, apply(data2.loc, 1, max) > threshold) 
pass2 <- both(apply(data2.cov, 2, max) > threshold, apply(data2.loc, 2, max) > threshold) 
data3 <- data2[pass1, pass2] 
data3.id <- data2.id[pass1, pass2]

#Create a list of colours that correspond to virus type. 
#if (colour.viruses || split == 'Virus') { 
h.virus <- hash(data$Virus, data$VirusGB) 
types <- vector() 
for (virus in rownames(data3)) {             
  types <- c(types,h.virus[[virus]]) 
} 
if (settings$colour.viruses) { 
  num_cols <- length(unique(types)) 
  if (num_cols <= 10) { 
    colours <- c('red', 'orange', 'green3', 'black', 'cyan3', 'blue', 'purple', 'gray', 'yellow2', 'magenta') 
  } else { 
    colours <- rainbow(num_cols) 
  } 
  virus_host_types <- c('vertebrates', 'invertebrates', 'plants', 'algae', 'diatom', 'fungi', 'archaea', 'environment', 'protozoa') 
  if (num_cols == 1 && types[1] %in% virus_host_types) { 
    h.cols <- hash(virus_host_types, c('blue', 'red', 'green3', 'cyan3', 'gray', 'black', 'purple', 'magenta', 'orange')) 
    colours <- h.cols[[types[1]]] 
  } 
  virus.cols <- colours[1:num_cols][as.numeric(factor(types))] 
  h.vcols <- hash(types, virus.cols) 
} else { 
  virus.cols <- rep('black', length(rownames(data3))) 
}

#Create a list of colours that correspond to host section. 
sections_table <- read.table(settings$ensembl.release.tdt, header = T, stringsAsFactors = F, sep = '\t', quote = '') 
h.host <- hash(sections_table$species, sections_table$section) 
h.cols <- hash(c("main", "metazoa", "plants", "fungi", "protists"), c("blue", "red", "green3", "black", "orange")) 
sections <- vector() 
host.cols <- vector() 
for (host in colnames(data3)) { 
  section <- h.host[[host]] 
  sections <- c(sections, section) 
  host.cols <- c(host.cols, h.cols[[section]]) 
}

#Convert virus names to aliases 
data3.aliases <- data3 
if (use.alias) { 
alias_table <- read.table(virus.tdt, header=T, stringsAsFactors=F, sep='\t', quote = '') 
alias_hash <- hash(alias_table$Virus, alias_table$Alias) 
aliases <- vector() 
for (virus in rownames(data3)) { 
aliases <- c(aliases,alias_hash[[virus]]) 
} 
rownames(data3.aliases) <- aliases 
}

#order the hosts and viruses alphabetically 
if (alphabetical) { 
types <- types[order(rownames(data3.aliases))] 
virus.cols <- virus.cols[order(rownames(data3.aliases))] 
data3.aliases <- data3.aliases[order(rownames(data3.aliases)), order(colnames(data3.aliases))] 
dendrogram = "none" 
} else { 
dendrogram = "both" 
}

#Plot the heatmap. 
filename <- sub("[.].*", "_all_sections.png", out.png) 
if (scale == -1) { 
scale <- ceiling((length(row.names(data3)) + 20)/150) 
} 
png(filename = filename, width = 3200, height = 1800 * scale, pointsize = 24) 
body(heatmap.2)[[62]][[3]][[2]] <- substitute(mtext(side = 4, at = iy, text = labRow, las = 2, line = -0.5 + offsetRow, cex = cexRow, adj = adjRow[1], padj = adjRow[2], col = virus.cols[rowInd])) 
body(heatmap.2)[[61]][[3]] <- substitute(mtext(side = 1, text = labCol, at = 1:nc, las = 2, line = -0.5 + offsetCol, cex = cexCol, adj = adjCol[1], col = host.cols[colInd])) 
body(heatmap.2)[[79]][[3]][[9]][[4]][[2]] <- substitute(min.raw <- 0) 
body(heatmap.2)[[79]][[3]][[9]][[4]][[3]] <- substitute(max.raw <- 100) 
body(heatmap.2)[[79]][[3]][[10]] <- substitute(z <- seq(min.raw, max.raw, length = length(heatmap.cols))) 
body(heatmap.2)[[79]][[3]][[11]] <- substitute(image(z = matrix(z, ncol = 1), col = heatmap.cols, breaks = breaks <- seq(min.raw, max.raw, length = (length(heatmap.cols) + 1)), xaxt = "n", yaxt = "n")) 
ddr <- tree(value, data3.id, row = TRUE, alphabetical) 
ddc <- tree(value, data3.id, row = FALSE, alphabetical) 
heatmap.cols = c('light blue', colorRampPalette(c("blue", "red", "yellow", "white"))(1000)) 
heatmap.2(data3.aliases, Rowv = ddr, Colv = ddc, dendrogram = dendrogram, key = T, keysize = 0.5, density.info = "none", trace = "none", margins = c(bottom.margin, right.margin), colsep = c(1:length(colnames(data3.aliases))), rowsep = c(1:length(rownames(data3.aliases))), sepwidth = c(0.05, 0.05), col = heatmap.cols[c((min(data3)*10):(max(data3)*10))], main = paste(value, ': all sections', sep = '')) 
par(xpd = NA) 
if (colour.viruses) { 
legend('bottomleft', unique(types)[order(unique(types))], text.col = unique(virus.cols)[order(unique(types))], cex = 0.7, title = 'Virus Group', title.col = 'black', inset = c(-0.02, -0.08/scale)) 
} 
legend('bottomleft', unique(sections), text.col = unique(host.cols), cex=0.7, title = 'Host Section', title.col = 'black', inset = c(0.03, -0.05/scale)) 
mtext(paste("v5", sub(' .*', '', Sys.time())), adj = 1, padj=-4) 
mtext(filename, adj = 0.1, col = 'red', padj=-4, cex = 0.8) 
dev.off()

#Plot separate heatmaps for each host section 
if (split == 'Host') { 
for (section in unique(sections)) { 
data4 <- data3[,sections == section] 
data4 <- data4[apply(data4, 1, max) > threshold, apply(data4, 2, max) > threshold] 
if (scale == -1) { 
scale <- ceiling((length(row.names(data4)) + 20)/150) 
} 
data4.id <- data3.id[,sections == section] 
data4.id <- data4.id[apply(data4.id, 1, max) > threshold, apply(data4.id, 2, max) > threshold] 
#Create a list of colours that correspond to virus type. 
if (colour.viruses) { 
types.section <- vector() 
virus.cols.section <- vector() 
for (virus in rownames(data4)) { 
type <- h.virus[[virus]] 
types.section <- c(types.section, type) 
virus.cols.section <- c(virus.cols.section, h.vcols[[type]]) 
} 
} else { 
virus.cols.section <- rep('black', length(rownames(data4))) 
} 
#Convert virus names to aliases 
if (use.alias) { 
aliases <- vector() 
for (virus in rownames(data4)) { 
aliases <- c(aliases,alias_hash[[virus]]) 
} 
rownames(data4) <- aliases 
} 
if (alphabetical) { 
virus.cols.section <- virus.cols.section[order(rownames(data4))] 
data4 <- data4[order(rownames(data4)), order(colnames(data4))] 
} 
#Plot heatmaps 
filename <- sub("[.].*", paste("_", section, ".png", sep=''), out.png) 
png(filename = filename, width = 3200, height = 1800 * scale, pointsize = 24) 
body(heatmap.2)[[61]][[3]] <- substitute(mtext(side = 1, text = labCol, at = 1:nc, las = 2, line = -0.5 + offsetCol, cex = min(0.2 + 1/log10(nc), 1), adj = adjCol[1], col = host.cols[sections == section][colInd])) 
body(heatmap.2)[[62]][[3]][[2]] <- substitute(mtext(side = 4, at = iy, text = labRow, las = 2, line = -0.5 + offsetRow, cex = min(0.2 + 1/log10(nr), 1.1), adj = adjRow[1], padj = adjRow[2], col = virus.cols.section[rowInd])) 
ddr <- tree(value, data4.id, row = TRUE, alphabetical) 
ddc <- tree(value, data4.id, row = FALSE, alphabetical) 
heatmap.2(data4, Rowv = ddr, Colv = ddc, dendrogram = dendrogram, key = T, keysize = 0.5, density.info = "none", trace = "none", margins = c(bottom.margin, right.margin), colsep = c(1:length(colnames(data4))), rowsep = c(1:length(rownames(data4))), sepwidth = c(0.05, 0.05), col = heatmap.cols[c((min(data4)*10):(max(data4)*10))], main = paste(value, ': ', section, sep='')) 
par(xpd = NA) 
if (colour.viruses) { 
legend('bottomleft', unique(types)[order(unique(types))], text.col = unique(virus.cols)[order(unique(types))], cex = 0.7, title = 'Virus Group', title.col = 'black', inset = c(-0.02, -0.08 * scale)) 
} 
legend('bottomleft', unique(sections)[order(unique(sections))], text.col = unique(host.cols)[order(unique(sections))], cex=0.7, title = 'Host Section', title.col = 'black', inset = c(0.03,-0.05 * scale)) 
mtext(paste("v5", sub(' .*', '', Sys.time())), adj = 1, padj=-4) 
mtext(filename, adj = 0.1, col = 'red', padj=-4, cex = 0.8) 
dev.off() 
} 
} else if (split == 'Virus') { 
for (type in unique(types)) { 
data4 <- data3.aliases[types == type,] 
data4 <- data4[apply(data4, 1, max) > threshold, apply(data4, 2, max) > threshold] 
if (scale == -1) { 
scale <- ceiling((length(row.names(data4)) + 20)/150) 
} 
data4.id <- data3.id[types == type,] 
data4.id <- data4.id[apply(data4.id, 1, max) > threshold, apply(data4.id, 2, max) > threshold] 
#Create a list of colours that correspond to virus type. 
if (colour.viruses) { 
virus.cols.type <- virus.cols[types == type] 
} else { 
virus.cols.type <- rep('black', length(rownames(data4))) 
} 
#Create a list of colours that correspond to host section. 
host.cols.type <- vector() 
for (host in colnames(data4)) { 
section <- h.host[[host]] 
host.cols.type <- c(host.cols.type, h.cols[[section]]) 
} 
#Plot heatmaps 
filename <- sub("[.].*", paste("_", type, ".png", sep=''), out.png) 
png(filename = filename, width = 3200, height = 1800 * scale, pointsize = 24) 
body(heatmap.2)[[61]][[3]] <- substitute(mtext(side = 1, text = labCol, at = 1:nc, las = 2, line = -0.5 + offsetCol, cex = min(0.2 + 1/log10(nc), 1), adj = adjCol[1], col = host.cols.type[colInd])) 
body(heatmap.2)[[62]][[3]][[2]] <- substitute(mtext(side = 4, at = iy, text = labRow, las = 2, line = -0.5 + offsetRow, cex = min(0.2 + 1/log10(nr), 1.1), adj = adjRow[1], padj = adjRow[2], col = virus.cols.type[rowInd])) 
ddr <- tree(value, data4.id, row = TRUE, alphabetical) 
ddc <- tree(value, data4.id, row = FALSE, alphabetical) 
heatmap.2(data4, Rowv = ddr, Colv = ddc, dendrogram = dendrogram, key = T, keysize = 0.5, density.info = "none", trace = "none", margins = c(bottom.margin, right.margin), colsep = c(1:length(colnames(data4))), rowsep = c(1:length(rownames(data4))), sepwidth = c(0.05, 0.05), col = heatmap.cols[c((min(data4)*10):(max(data4)*10))], main = paste(value, ': ', type, sep='')) 
par(xpd = NA) 
if (colour.viruses) { 
legend('bottomleft', unique(types)[order(unique(types))], text.col = unique(virus.cols)[order(unique(types))], cex = 0.7, title = 'Virus Group', title.col = 'black', inset = c(-0.02, -0.08 * scale)) 
} 
legend('bottomleft', unique(sections)[order(unique(sections))], text.col = unique(host.cols)[order(unique(sections))], cex=0.7, title = 'Host Section', title.col = 'black', inset = c(0.03, -0.05 * scale)) 
mtext(paste("v5", sub(' .*', '', Sys.time())), adj = 1, padj=-4) 
mtext(filename, adj = 0.1, col = 'red', padj=-4, cex = 0.8) 
dev.off() 
} 
}

#plot scatterplot 
if (scatter) { 
host.cols.scatter <- vector() 
for (host in data$Genome) { 
section <- h.host[[host]] 
host.cols.scatter <- c(host.cols.scatter, h.cols[[section]]) 
} 
filename <- sub("[.].*", "_scatter.png", out.png) 
png(filename = filename, width = 900, height = 900, pointsize = 24) 
plot(data$Coverage, data$Local, col = host.cols.scatter, xlab = 'Coverage', ylab = 'Local Identity', xlim = c(0, 100), ylim = c(0, 100)) 
legend('bottomright', unique(sections)[order(unique(sections))], col = unique(host.cols)[order(unique(sections))], cex=0.7, title = 'Host Section', title.col = 'black', inset = c(0.01,0.01), pch=1) 
mtext(paste("v2", sub(' .*', '', Sys.time())), adj = 1, padj=-4, cex = 0.5) 
mtext(filename, adj = 0, col = 'red', padj=-4, cex = 0.5) 
dev.off() 
}

