########################################################
### Tree PNG Generator                         ~~~~~ ###
### VERSION: 0.1.0                             ~~~~~ ###
### LAST EDIT: 26/08/15                        ~~~~~ ###
### AUTHORS: Richard Edwards 2015              ~~~~~ ###
### CONTACT: richard.edwards@unsw.edu.au       ~~~~~ ###
########################################################

################# ::: HISTORY ::: ######################
# v0.1.0 : Initial version based on old rje_tree.R.

############### ::: GENERAL SETUP ::: ##################
# Usage = Rscript rje.r tree basefile [options] 

## ~ Read commandline arguments ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ##
rtype = arglist$rtype          # arglist is generated by rje.r
(basefile = arglist$basefile)  # arglist is generated by rje.r

## ~ Set up global parameters and file names ~~~~~~~~~~~~~~~~~~~~~~~~~~ ##
settings = list(basefile=basefile)   # Access with settings[["basefile"]] or settings$basefile
settings$pngwidth = 1600
settings$pngheight = 1600   #!# Not currently used. Set as max height?
settings$pointsize = 14
settings$treetitle = basefile
settings$lwd = 2

# Update default settings from commandline arguments (setting=value)
(arglist)  # This contains settings read in from arguments
#arglist = argBool(arglist,c("assessment","covplot"))    # List of Boolean settings
arglist = argNum(arglist,c("pngwidth","pngheight","pointsize","lwd"))     # List of numeric settings
#arglist = argList(arglist,c("plotft"))
for(cmd in names(arglist)){
  settings[[cmd]] = arglist[[cmd]]  # Need to add processing of booleans etc.
}
(settings)  # This contains settings read in from arguments

# Setup base filenames for outputs
settings$csvfile = paste(basefile,'r.csv',sep=".")
settings$pngfile = paste(basefile,'png',sep=".")

## ~ Set up tree data ~~~~~~~~~~~~~~~~~~~~~~~~~~ ##
# Load CSV file and set limits
tree = read.csv(settings$csvfile)
ynum = length(tree$xpos)
x = 1 / (2*max(tree$xpos))
y = 1 / (ynum+1)

# Families and colours ###
fcolist = c(1:4,8:21)
tree$fcol = "black"       # soton$col[1]	#"black"
#flvl = levels(as.factor(tree[tree$family != "EHUX",]$family))
flvl = levels(as.factor(tree$family))
if(length(flvl) > 0){
                for (f in 1:length(flvl)){ tree[tree$family == flvl[f],]$fcol = soton$col[fcolist[f]] }
}
#~special~#
#!# Add as else and use if length(flvl) == 1 and only level is empty text?
#!# Better still, encode better colour information in rje_tree.py!
#tree[tree$family == "EHUX",]$fcol = soton$col[5]

#!# Can we add some special family features as arguments? #!#

### ~ Setup Plot ~ ###
yex = 100 #38
ypx = 20 #50
mex = 2  #1
png(filename = settings$pngfile, width = settings$pngwidth, height = max(300,(ynum+2)*ypx), units = "px", pointsize=settings$pointsize)
plot(0:1,0:1,type="n",axes=FALSE,ann=FALSE,mar=c(0,1,4,1))
title(main=settings$treetitle)

### ~ Draw Tree ~ ###
for (i in 1:ynum){
	data = tree[i,]
	lines(c(data$xpos*x,data$ancx*x),c(1-data$ypos*y,1-data$ypos*y),col=data$fcol,lwd=settings$lwd)
	lines(c(data$ancx*x,data$ancx*x),c(1-data$ypos*y,1-data$ancy*y),col=data$fcol,lwd=settings$lwd)
}
### ~ Add Text ~ ###
for (i in 1:ynum){
	data = tree[i,]
	if (data$nodenum <= ((ynum+1) / 2)){
		#text((data$xpos)*x+0.01,1-data$ypos*y,data$name,adj=c(0,0.5),cex=min(mex,(yex+2)/ynum),col=data$fcol)
		text((data$xpos)*x+0.01,1-data$ypos*y,data$name,adj=c(0,0.5),col=data$fcol)
	}else{
		#text((data$xpos)*x-0.01,1+(0.45/ynum)-data$ypos*y,data$boot,adj=c(1,0),cex=min(mex,yex/ynum),col=soton$col[5])
		text((data$xpos)*x-0.01,1+(0.45/ynum)-data$ypos*y,data$boot,adj=c(1,0),cex=0.8,col=soton$col[5])
	}
}
### ~ Add scale ~ ###
scalex = 0.1
if(max(tree$xpos) > 4){ scalex = 1 }
if(max(tree$xpos) > 40){ scalex = 10 }
lines(c(0,scalex*x),c(0,0),col=soton$col[7],lwd=settings$lwd)
lines(c(0,0),c(0,-0.005),col=soton$col[7],lwd=settings$lwd)
lines(c(scalex*x,scalex*x),c(0,-0.005),col=soton$col[7],lwd=settings$lwd)
#text(0,-0.01,"0",adj=c(0.5,1),cex=min(mex,yex/ynum),col=soton$col[7],xpd=NA)
#text(0.1*x,-0.01,"0.1",adj=c(0.5,1),cex=min(mex,yex/ynum),col=soton$col[7],xpd=NA)
text(0,-0.01,"0",adj=c(0.5,1),col=soton$col[7],xpd=NA)
text(scalex*x,-0.01,scalex,adj=c(0.5,1),col=soton$col[7],xpd=NA)

dev.off()
